### ISSUE TITLE
Export data from different numbering systems

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#167]
`ruby-cldr` currently only exports data from the `latn` numbering system, and the structure of the output data files doesn't have a place to support the exporting of the other numbering systems.

```yaml
bn:
  numbers:
    symbols: # Implicitly `latn`
      alias: ''
      decimal: "."
      group: ","
      list: ";"
      percent_sign: "%"
      ....
```

perhaps we'd want to restructure things such that the numbering system is part of the keypath:

```yaml
bn:
  numbers:
    symbols:
      beng:
          ....
      latn:
          ....
```

or 

```yaml
bn:
  numbers:
    beng:
      symbols:
          ....
    latn:
      symbols:
          ....
```

**Note:** There are a [number of aliases](https://github.com/unicode-org/cldr/blob/86fd8773ed0f3c4da15be368d2ba3b5683ed9f93/common/main/root.xml#L3041-L3064) in the `root` locale that would need to be implemented once we start exporting the other numbering systems
