### ISSUE TITLE
Sort keys within the components

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#197]
As part of #82, we started sorting at the `Export` level.

This was nice for consistent output, but ended up changing the order of things that already have a logical sort order.

For example, the output of `Calendars` has had the order of the weekdays mangled as a result:

```yaml
wide:
  fri: Friday
  mon: Monday
  sat: Saturday
  sun: Sunday
  thu: Thursday
  tue: Tuesday
  wed: Wednesday
```
