### ISSUE TITLE
Don't mix results from different number systems

### ISSUE THREAD

**Issue by movermeyer** [ruby-i18n/ruby-cldr#89]
`ar` has information on percent formatting for two number systems: `arab` and `latn`.

`Cldr::Export::Data::Numbers#number_system` takes the first one arbitrarily as the value of `number_system`:

https://github.com/ruby-i18n/ruby-cldr/blob/c85848a75d962eb4e72b9147861afdc0f361cc52/lib/cldr/export/data/numbers.rb#L103-L106

This results in exports that:

a) are missing the `latn` data, due to being shadowed by the `arab` data
b) mis-label the `latn` data as `arab`

```
thor cldr:export --components=Numbers --locales=ar
```

```yaml
decimal:
  number_system: arab
  patterns:
    default: "#,##0.###`" # From `arab`, shadowing the similar data from `latn`
    long: # Everything else is from `latn`
      '1000': 
        few: 0 آلاف # From `latn`
        many: 0 ألف # From `latn`
        one: 0 ألف # From `latn`
        other: 0 ألف # From `latn`
        two: 0 ألف # From `latn`
        zero: 0 ألف # From `latn`
      '10000':
        few: 00 ألف # From `latn`
        many: 00 ألف # From `latn`
        one: 00 ألف # From `latn`
        other: 00 ألف # From `latn`
        two: 00 ألف # From `latn`
        zero: 00 ألف # From `latn`
```

### Potential solution

Add an additional layer of nesting to the YAML output that contains the number system:

```yaml
decimal:
  arab:
    patterns:
      default: "#,##0.###`" # From `arab`
  latn:
    patterns:
      default: "#,##0.###`" # From `latn`
      long:
        '1000': 
          few: 0 آلاف # From `latn`
          many: 0 ألف # From `latn`
          one: 0 ألف # From `latn`
          other: 0 ألف # From `latn`
          two: 0 ألف # From `latn`
          zero: 0 ألف # From `latn`
```

This would more closely match the upstream CLDR data, and avoid these problems.
